### ISSUE TITLE
Doesn't work with config

### ISSUE THREAD

**Issue by wafcio** [avdi/dotenv_elixir#21]
Variables from .env are available after run server. In config (for example database config) variables from .env aren't available.

I checked it in phoenix sample app.

**Comment by jarednorman** [comment]
It is not possible to make them available at compile time using a lib like this. You will need to ensure things are set in the environment yourself if you need them at compile time. Unfortunately, that does make this library less useful than it's counterparts in other languages.

**Comment by HangingClowns** [comment]
just found this problem out the hard way. Can you write this on the README? quite annoying :(

**Comment by joshjung** [comment]
This is so frustrating. I'm fairly new to Elixir but this build setup is so shortsighted. Is there a way I could force the loading of the .env file using the library inside the config itself?

**Comment by wafcio** [comment]
This hex is a bit wrong designed, you can consider to use envy

**Comment by HangingClowns** [comment]
@joshjung what are you trying to do? why not source your .dotenv file yourself then run mix commands?

**Comment by jarednorman** [comment]
I believe this issue is explained in the warning in the README, but if anyone has suggestions for making it more clear, I'd love to hear them.

I, the maintainer of this project, recommend not using this project. It's not a good way to manage configuration in Elixir apps. The issues you're encountering are because of this.

Envy could be a better option if you really want to do something like this, but I've not used it.
